# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      all:
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: gomod
    directory: "./"
    schedule:
      interval: "daily"
    groups:
      all:
        update-types:
          - "patch"
  - package-ecosystem: terraform
    directory: "/iac"
    schedule:
      interval: "daily"
    groups:
      all:
        update-types:
          - "patch"
  - package-ecosystem: terraform
    directory: "/modules/app"
    schedule:
      interval: "daily"
    groups:
      all:
        update-types:
          - "patch"
  - package-ecosystem: terraform
    directory: "/iac/bootstrap"
    schedule:
      interval: "daily"
    groups:
      all:
        update-types:
          - "patch"
