---
linters:
  enable:
    - asciicheck
    - unused
    - errcheck
    - errorlint
    - gofmt
    - goimports
    - gosec
    - gocritic
    - importas
    - prealloc
    - revive
    - misspell
    - stylecheck
    - tparallel
    - unconvert
    - unparam
    - whitespace
issues:
  uniq-by-line: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0
linters-settings:
  revive:
    rules:
      - name: dot-imports
        disabled: true
run:
  issues-exit-code: 1
  timeout: 10m
