# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Boilerplate

on:
  pull_request:
    branches:
      - 'main'

permissions: {}

jobs:

  check:
    permissions:
      contents: read

    name: Boilerplate Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Keep running if one leg fails.
      matrix:
        extension:
        - go
        - sh
        - yaml

        # Map between extension and human-readable name.
        include:
        - extension: go
          language: Go
        - extension: sh
          language: Bash
        - extension: yaml
          language: YAML

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: chainguard-dev/actions/boilerplate@e9290faa91aa6b1226df129cb450f2ff49235b92 # v1.6.6
        with:
          extension: ${{ matrix.extension }}
          language: ${{ matrix.language }}
          exclude: pkg/webhook/testdata
