# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Do Not Submit

on:
  pull_request:
    branches:
      - 'main'

permissions: {}

jobs:

  donotsubmit:
    name: Do Not Submit
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: block
          allowed-endpoints: >
            *.blob.core.windows.net:443
            *.githubapp.com:443
            api.github.com:443
            github.com:443
            release-assets.githubusercontent.com:443

      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Do Not Submit
        uses: chainguard-dev/actions/donotsubmit@c29bd2a0f4e71ad61a209c255c0164987df76aaa # v1.6.10
