# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: go-build-test

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

permissions: {}

jobs:

  go-build-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: block
          allowed-endpoints: >
            *.blob.core.windows.net:443
            *.githubapp.com:443
            accounts.google.com:443
            api.github.com:443
            dl.google.com:443
            github.com:443
            go.dev:443
            issuer.enforce.dev:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            release-assets.githubusercontent.com:443
            storage.googleapis.com:443
            sum.golang.org:443

      - name: Check out code onto GOPATH
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: '${{ github.workspace }}/.go-version'
          check-latest: true
          cache: 'false'

      - name: build
        run: |
          go build -o octo-sts ./cmd/app

      - name: test
        run: |
          # Exclude running unit tests against third_party repos.
          go test -v -race ./...
