# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: terraform-validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  terraform-lint-validate:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      matrix:
        terraform-dir:
          - ./env/octo-sts/bootstrap
          - ./env/octo-sts
          - ./env/octo-sts-staging

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: block
          allowed-endpoints: >
            *.blob.core.windows.net:443
            *.githubapp.com:443
            checkpoint-api.hashicorp.com:443
            github.com:443
            registry.terraform.io:443
            release-assets.githubusercontent.com:443
            releases.hashicorp.com:443

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - uses: chainguard-dev/actions/setup-terraform@5f020827ba80ff5d64d45116542d0c733e8e7e71 # v1.6.23
        with:
          terraform-version-file: "${{ github.workspace }}/.terraform-version"
          terraform-wrapper: false

      - run: cp "$GITHUB_WORKSPACE/.github/testdata/backend_override.tf" "$GITHUB_WORKSPACE/${{ matrix.terraform-dir }}"
      - working-directory: ${{ matrix.terraform-dir }}
        run: |
          terraform init
          terraform validate
