# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: terraform-validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  terraform-lint-validate:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      matrix:
        terraform-dir:
          - ./env/octo-sts/bootstrap
          - ./env/octo-sts
          - ./env/octo-sts-staging

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: block
          allowed-endpoints: >
            *.blob.core.windows.net:443
            *.githubapp.com:443
            checkpoint-api.hashicorp.com:443
            github.com:443
            registry.terraform.io:443
            release-assets.githubusercontent.com:443
            releases.hashicorp.com:443

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: chainguard-dev/actions/setup-terraform@f0be69916b439d0fcced2451b23d0f27cd46d545 # v1.6.26
        with:
          terraform-version-file: "${{ github.workspace }}/.terraform-version"
          terraform-wrapper: false

      - env:
          TERRAFORM_DIR: ${{ matrix.terraform-dir }}
        run: cp "$GITHUB_WORKSPACE/.github/testdata/backend_override.tf" "$GITHUB_WORKSPACE/${TERRAFORM_DIR}"
      - working-directory: ${{ matrix.terraform-dir }}
        run: |
          terraform init
          terraform validate
